# Generated by Django 5.2.5 on 2025-12-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0004_alter_employeesalary_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalary',
            name='month',
            field=models.DateField(blank=True, null=True),
        ),
    ]
